/* kagizine -- Kagi News as a page-turning magazine.
 *
 * Two jobs.
 *
 * `scheduled` builds the day's edition: fetch the four feeds, parse and sanitise
 * them, store the pictures, write the edition to R2. It fires twice daily
 * because cron triggers are UTC-only and Kagi rebuilds at 08:00 Eastern, which
 * is 12:00 UTC in summer and 13:00 in winter; the second firing finds nothing
 * new and returns in a fraction of a second. See `refresh`.
 *
 * `fetch` serves the reader: static files come from the Assets binding without
 * touching this code, and everything else is a small JSON API over R2.
 */

import * as build from './kagi/build';
import { FEEDS } from './kagi/feed';
import { now } from './kagi/feed';
import * as store from './kagi/store';

export interface Env {
  EDITIONS: R2Bucket;
  ASSETS: Fetcher;
  REFRESH_TOKEN?: string;
}

// Paths the Worker owns. Anything else is a static file and never reaches here.
const IMG_RE = /^\/img\/([0-9a-f]{64}\.[a-z]{3,4})$/;
const EDITION_RE = /^\/api\/editions\/(\d{4}-\d{2}-\d{2})$/;
const REPORT_RE = /^\/api\/reports\/(\d{4}-\d{2}-\d{2})$/;

/** Outbound request deadline. Feeds and pictures both go through it.
 *
 * Deliberately generous, because a tight one has already caused an outage here:
 * 10 seconds looked ample and lost *every* picture in the edition, twice over --
 * each abort looking transient, so each was retried.
 *
 * What is odd, and unexplained, is why: the image proxy answers a plain curl in
 * 300-400ms, yet the in-Worker image phase has measured 60-120 seconds for
 * ~31 pictures across every implementation of this build, Python and TypeScript
 * alike. It is not the User-Agent (tested) and not the proxy being slow
 * (measured). Until that is understood this value is a backstop against a host
 * that never answers, not a latency budget -- and the refresh now reports median
 * and slowest picture times so the next unattended run can settle it. */
const FETCH_TIMEOUT_MS = 45_000;

/** A ceiling on what one response may be read into memory.
 *
 *  The URLs come from feed content, so their size is chosen by whoever controls
 *  the feed. An isolate has 128MB; a single multi-hundred-megabyte body would
 *  take the build down with it every day until the feed changed. */
const MAX_BODY_BYTES = 12 * 1024 * 1024;

/* Same posture as public/_headers, repeated here because responses generated by
 * the Worker bypass that file entirely.
 *
 * The CSP is defence in depth rather than a fix: no route here can serve an HTML
 * document (everything is JSON or one of four image types, all with `nosniff`),
 * so there is no context for a policy to constrain -- but `default-src 'none'`
 * costs nothing and closes the gap if that ever stops being true. */
const SECURITY_HEADERS: Record<string, string> = {
  'x-content-type-options': 'nosniff',
  'referrer-policy': 'strict-origin-when-cross-origin',
  'x-frame-options': 'DENY',
  'content-security-policy': "default-src 'none'; base-uri 'none'; form-action 'none'",
  'cross-origin-resource-policy': 'same-origin',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
};

function jsonResponse(body: string, cache: string, status = 200): Response {
  return new Response(body, {
    status,
    headers: {
      ...SECURITY_HEADERS,
      'content-type': 'application/json; charset=utf-8',
      'cache-control': cache,
    },
  });
}

function error(status: number, message: string): Response {
  return jsonResponse(JSON.stringify({ error: message }), 'no-store', status);
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const path = new URL(request.url).pathname.replace(/\/+$/, '') || '/';

    if (path === '/api/editions') {
      const body = await store.getText(env.EDITIONS, store.INDEX_KEY);
      // A bucket with nothing in it is a real state on the first deploy, and the
      // reader has a message for it -- so this is an empty index, not a 404.
      if (body === null) {
        return jsonResponse(JSON.stringify({ generated_at: null, editions: [] }), 'no-store');
      }
      return jsonResponse(body, 'public, max-age=300');
    }

    const edition = EDITION_RE.exec(path);
    if (edition) {
      const body = await store.getText(env.EDITIONS, store.editionKey(edition[1]!));
      if (body === null) return error(404, 'no edition for that date');
      // A past edition never changes; today's is rewritten once, in the morning.
      return jsonResponse(body, 'public, max-age=300');
    }

    // The refresh keeps a report per day; until now nothing could read one, so a
    // feed that failed on a Tuesday was discovered by noticing a thin edition.
    // Public because it contains no secrets -- feed URLs that are already public,
    // counts, timings, and the warnings the build raised.
    const report = REPORT_RE.exec(path);
    if (report) {
      const body = await store.getText(env.EDITIONS, store.reportKey(report[1]!));
      if (body === null) return error(404, 'no report for that date');
      return jsonResponse(body, 'public, max-age=300');
    }

    const image = IMG_RE.exec(path);
    if (image) return serveImage(env, image[1]!);

    if (path === '/admin/refresh') return adminRefresh(request, env);

    if (path === '/api/health') {
      const index = await store.readIndex(env.EDITIONS);
      const latest = index.editions[0]?.date ?? null;
      // Carries the last build's outcome, so one request answers "did this
      // morning go well?" without reading a 290KB edition.
      const last = latest
        ? await store.getJson<build.Report>(env.EDITIONS, store.reportKey(latest))
        : null;
      return jsonResponse(
        JSON.stringify({
          ok: true,
          editions: index.editions.length,
          latest,
          last_refresh: last
            ? {
                finished_at: last.finished_at,
                articles: last.articles,
                pictures: last.pictures,
                pictures_expected: last.pictures_expected,
                failed_feeds: last.failures.map((f) => f.feed),
                warnings: last.warnings.length,
                picture_ms_median: last.image_ms_median,
                picture_ms_slowest: last.image_ms_slowest,
                images_ms: last.images_ms,
              }
            : null,
        }),
        'no-store'
      );
    }

    return error(404, 'not found');
  },

  async scheduled(_controller: ScheduledController, env: Env, _ctx: ExecutionContext) {
    try {
      const result = await refresh(env);
      console.log(`refresh: ${JSON.stringify(result)}`);
    } catch (e) {
      // Throwing here would mark the invocation failed and retry it; for a daily
      // feed a loud log and the next firing are the better answer.
      console.error(`refresh failed: ${(e as Error).message ?? e}`);
    }
  },
};

/**
 * Serve one picture straight out of R2.
 *
 * The R2 object's body stream is handed to the Response untouched, so the bytes
 * are never read into the Worker. Keys are content hashes, which is what makes
 * `immutable` honest: these bytes cannot change, only be replaced by a
 * different key.
 */
async function serveImage(env: Env, asset: string): Promise<Response> {
  const object = await env.EDITIONS.get(store.imageKey(asset));
  if (!object) return error(404, 'no such picture');
  return new Response(object.body, {
    headers: {
      ...SECURITY_HEADERS,
      'content-type': object.httpMetadata?.contentType ?? 'application/octet-stream',
      'cache-control': 'public, max-age=31536000, immutable',
    },
  });
}

/**
 * Rebuild on demand, for seeding a new deployment and for recovery.
 *
 * Gated on a bearer token rather than left open: it is a write path that makes
 * around thirty-five outbound requests, so an unauthenticated caller could use
 * the Worker to hammer the feeds. Absent the secret the route does not exist,
 * which is the safe direction to fail.
 */
async function adminRefresh(request: Request, env: Env): Promise<Response> {
  const expected = env.REFRESH_TOKEN;
  if (!expected) return error(404, 'not found');
  if (request.method !== 'POST') return error(405, 'POST only');

  const offered = request.headers.get('authorization') ?? '';
  if (!(await secretsMatch(offered, `Bearer ${expected}`))) return error(401, 'unauthorized');

  const force = new URL(request.url).searchParams.has('force');
  try {
    return jsonResponse(JSON.stringify(await refresh(env, force)), 'no-store');
  } catch (e) {
    return error(502, `refresh failed: ${(e as Error).message ?? e}`);
  }
}

/**
 * Build today's edition and publish it.
 *
 * Idempotent by design, because the cron fires twice a day and a manual refresh
 * can land at any time: the feeds state when they were last built, and if a
 * stored edition already came from that same build there is nothing to do.
 */
export async function refresh(env: Env, force = false): Promise<Record<string, unknown>> {
  const bucket = env.EDITIONS;
  const started = now();

  const isCurrent = async (date: string, builtFrom: string) => {
    if (force || !builtFrom) return false;
    const existing = await store.getJson<store.StoredDay>(bucket, store.editionKey(date));
    return Boolean(existing?.edition.built_from && existing.edition.built_from === builtFrom);
  };

  let built;
  try {
    built = await build.buildEdition(
      (url) => fetchBytes(url),
      (asset, data, mime) => store.putImage(bucket, asset, data, mime),
      FEEDS,
      isCurrent
    );
  } catch (e) {
    if (e instanceof build.Unchanged) {
      return { status: 'unchanged', date: e.date, built_from: e.builtFrom };
    }
    throw e;
  }

  const { edition, articles, report } = built;
  edition.fetched_at = started;
  await store.putJson(bucket, store.editionKey(edition.date), { edition, articles });

  report.started_at = started;
  report.finished_at = now();
  await store.putJson(bucket, store.reportKey(edition.date), report);

  await store.upsertIndex(bucket, edition, Object.keys(articles).length, now());
  const pruned = await store.prune(bucket, now());

  return {
    status: 'published',
    date: edition.date,
    articles: report.articles,
    sections: report.sections,
    pictures: report.pictures,
    failures: report.failures,
    warnings: report.warnings.length,
    // Surfaced because the cron logs this: a rising retry count is the early
    // warning that the image proxy is getting flaky.
    image_retries: report.image_retries,
    ms: { feeds: report.feeds_ms, images: report.images_ms, articles: report.articles_ms },
    picture_ms: { median: report.image_ms_median, slowest: report.image_ms_slowest },
    pictures_expected: report.pictures_expected,
    pruned,
  };
}

/** The injected fetch the build runs on. Feeds and pictures are both just bytes
 *  here, which is why the build never needs to know which it is asking for. */
async function fetchBytes(url: string) {
  const response = await fetch(url, {
    headers: { 'user-agent': 'kagizine/1.0 (personal reader)' },
    // Without a deadline a slow host holds one of six concurrency slots for as
    // long as it likes, and a build can hang rather than fail.
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
  });
  // Typed, so the image retry can tell a refusal from a dropped connection.
  if (response.status !== 200) throw new build.HttpStatusError(response.status, url);
  // Content-Length is advisory -- it can be absent or lie -- so the declared
  // size is only a cheap early exit, and the real check is on what arrived.
  const declared = Number(response.headers.get('content-length') ?? '0');
  if (declared > MAX_BODY_BYTES) {
    throw new Error(`body too large (${declared} bytes declared) for ${url}`);
  }
  const data = new Uint8Array(await response.arrayBuffer());
  if (data.length > MAX_BODY_BYTES) {
    throw new Error(`body too large (${data.length} bytes) for ${url}`);
  }
  return { data, contentType: response.headers.get('content-type') };
}

/** Compare two secrets without revealing anything about the wrong one.
 *
 * Digests first, then a fixed-length comparison with no early return. Comparing
 * the strings directly had to bail on a length mismatch, which made the token's
 * length observable in the response timing -- a small leak, but one this removes
 * for two lines. */
async function secretsMatch(a: string, b: string): Promise<boolean> {
  const encoder = new TextEncoder();
  const [left, right] = await Promise.all([
    crypto.subtle.digest('SHA-256', encoder.encode(a)),
    crypto.subtle.digest('SHA-256', encoder.encode(b)),
  ]);
  const x = new Uint8Array(left);
  const y = new Uint8Array(right);
  let mismatch = 0;
  for (let i = 0; i < x.length; i++) mismatch |= x[i]! ^ y[i]!;
  return mismatch === 0;
}
