"""kagizine -- Kagi News as a page-turning magazine.

A Python Worker with two jobs.

`scheduled` builds the day's edition: fetch the four feeds, parse and sanitise
them, store the pictures, write the edition to R2. It fires twice daily because
cron triggers are UTC-only and Kagi rebuilds at 08:00 Eastern, which is 12:00
UTC in summer and 13:00 in winter; the second firing finds nothing new and
returns. See `refresh` for how that is decided.

`fetch` serves the reader: static files come from the Assets binding without
touching this code, and everything else is a small JSON API over R2.

The parsing and sanitising live in `kagi/`, are pure, and are the same code the
test suite runs under CPython. Choosing Python for the Worker is what buys that
-- there is one implementation of the feed format, not a local one and a
deployed one drifting apart.
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone

from js import Object
from js import Response as JSResponse
from pyodide.ffi import to_js
from workers import Response, WorkerEntrypoint, fetch

from kagi import build, store
from kagi.feed import FEEDS

# Paths the Worker owns. Anything else is a static file and never reaches here.
IMG_RE = re.compile(r"^/img/([0-9a-f]{64}\.[a-z]{3,4})$")
EDITION_RE = re.compile(r"^/api/editions/(\d{4}-\d{2}-\d{2})$")

# Same posture as the static `_headers` file, repeated here because responses
# generated by the Worker bypass that file entirely.
SECURITY_HEADERS = {
    "x-content-type-options": "nosniff",
    "referrer-policy": "strict-origin-when-cross-origin",
    "x-frame-options": "DENY",
}


def json_response(payload: str, *, cache: str, status: int = 200) -> Response:
    headers = dict(SECURITY_HEADERS)
    headers["content-type"] = "application/json; charset=utf-8"
    headers["cache-control"] = cache
    return Response(payload, status=status, headers=headers)


def error(status: int, message: str) -> Response:
    return json_response(json.dumps({"error": message}), cache="no-store", status=status)


def now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


class Default(WorkerEntrypoint):
    # ------------------------------------------------------------------ http

    async def fetch(self, request):
        url_path = _path(request)

        if url_path == "/api/editions":
            body = await store.get_text(self.env.EDITIONS, store.INDEX_KEY)
            if body is None:
                # A bucket with nothing in it is a real state on the first
                # deploy, and the reader has a message for it -- so this is an
                # empty index, not a 404.
                return json_response(
                    json.dumps({"generated_at": None, "editions": []}), cache="no-store"
                )
            return json_response(body, cache="public, max-age=300")

        match = EDITION_RE.match(url_path)
        if match:
            body = await store.get_text(self.env.EDITIONS, store.edition_key(match.group(1)))
            if body is None:
                return error(404, "no edition for that date")
            # A past edition never changes; today's is rewritten once, in the
            # morning. Five minutes covers the difference without making the
            # reader wait on R2 for every navigation.
            return json_response(body, cache="public, max-age=300")

        match = IMG_RE.match(url_path)
        if match:
            return await self._image(match.group(1))

        if url_path == "/admin/refresh":
            return await self._refresh(request)

        if url_path == "/api/health":
            index = await store.read_index(self.env.EDITIONS)
            latest = index["editions"][0]["date"] if index["editions"] else None
            return json_response(
                json.dumps({"ok": True, "editions": len(index["editions"]), "latest": latest}),
                cache="no-store",
            )

        return error(404, "not found")

    async def _image(self, asset: str) -> Response:
        """Serve one picture straight out of R2.

        The R2 object's body stream is handed to a JS Response and returned as
        is, so the bytes never enter the interpreter. Keys are content hashes,
        which is what makes `immutable` honest: these bytes cannot change, only
        be replaced by a different key.
        """
        obj = await store.get_object(self.env.EDITIONS, store.image_key(asset))
        if obj is None:
            return error(404, "no such picture")
        headers = dict(SECURITY_HEADERS)
        headers["content-type"] = store.content_type_of(obj)
        headers["cache-control"] = "public, max-age=31536000, immutable"
        return Response(
            JSResponse.new(obj.body, to_js({"headers": headers}, dict_converter=Object.fromEntries))
        )

    async def _refresh(self, request) -> Response:
        """Rebuild on demand, for seeding a new deployment and for recovery.

        Gated on a bearer token rather than left open: it is a write path that
        makes ~35 outbound requests, so an unauthenticated caller could use the
        Worker to hammer the feeds. Absent the secret the route does not exist,
        which is the safe direction to fail.
        """
        expected = getattr(self.env, "REFRESH_TOKEN", None)
        if not expected:
            return error(404, "not found")
        if request.method != "POST":
            return error(405, "POST only")

        offered = request.headers.get("authorization") or ""
        if not _tokens_match(offered, "Bearer %s" % expected):
            return error(401, "unauthorized")

        force = "force" in (_query(request) or "")
        try:
            result = await self.refresh(force=force)
        except Exception as e:
            return error(502, "refresh failed: %s" % e)
        return json_response(json.dumps(result), cache="no-store")

    # ------------------------------------------------------------------ cron

    async def scheduled(self, controller, env, ctx):
        # All four parameters are required by the runtime, unlike fetch().
        try:
            result = await self.refresh()
            print("refresh: %s" % json.dumps(result))
        except Exception as e:
            # Raising here would mark the invocation failed and retry; for a
            # daily feed a loud log and the next firing are the better answer.
            print("refresh failed: %s" % e)

    # ------------------------------------------------------------- the build

    async def refresh(self, *, force: bool = False) -> dict:
        """Build today's edition and publish it.

        Idempotent by design, because the cron fires twice a day and a manual
        refresh can land at any time: the feeds state when they were last
        built, and if a stored edition already came from that same build there
        is nothing to do.
        """
        bucket = self.env.EDITIONS
        started = now()

        async def is_current(date: str, built_from: str) -> bool:
            if force or not built_from:
                return False
            existing = await store.get_json(bucket, store.edition_key(date))
            return bool(
                existing
                and existing["edition"].get("built_from")
                and existing["edition"]["built_from"] == built_from
            )

        try:
            edition, articles, report = await build.build_edition(
                _fetch_bytes,
                lambda key, data, mime: store.put_image(bucket, key, data, mime),
                FEEDS,
                is_current,
            )
        except build.Unchanged as e:
            return {"status": "unchanged", "date": e.date, "built_from": e.built_from}

        edition["fetched_at"] = started
        await store.put_json(
            bucket, store.edition_key(edition["date"]), {"edition": edition, "articles": articles}
        )

        report["started_at"] = started
        report["finished_at"] = now()
        await store.put_json(bucket, store.report_key(edition["date"]), report)

        await store.upsert_index(bucket, edition, len(articles), now())
        pruned = await store.prune(bucket, generated_at=now())

        return {
            "status": "published",
            "date": edition["date"],
            "articles": report["articles"],
            "sections": report["sections"],
            "pictures": report["pictures"],
            "failures": report["failures"],
            "warnings": len(report["warnings"]),
            "seconds": {
                "feeds": report.get("feeds_seconds"),
                "images": report.get("images_seconds"),
                "articles": report.get("articles_seconds"),
            },
            "pruned": pruned,
        }


# ----------------------------------------------------------------- plumbing


async def _fetch_bytes(url: str):
    """The injected fetch the build runs on.

    `urllib` cannot work in a Worker -- there are no sockets -- so every
    outbound request goes through the runtime's fetch. Feeds and pictures are
    both just bytes here, which is why the build never needs to know which it
    is asking for.
    """
    response = await fetch(url, headers={"user-agent": "kagizine/1.0 (personal reader)"})
    if response.status != 200:
        raise RuntimeError("HTTP %d for %s" % (response.status, url))
    return await response.bytes(), response.headers.get("content-type")


def _path(request) -> str:
    """The request path, without query or host."""
    raw = str(request.url)
    without_scheme = raw.split("://", 1)[-1]
    path = "/" + without_scheme.partition("/")[2]
    return path.split("?", 1)[0].split("#", 1)[0].rstrip("/") or "/"


def _query(request) -> str:
    return str(request.url).partition("?")[2]


def _tokens_match(a: str, b: str) -> bool:
    """Constant-time-ish comparison, so a wrong token leaks no prefix length."""
    if len(a) != len(b):
        return False
    mismatch = 0
    for x, y in zip(a, b):
        mismatch |= ord(x) ^ ord(y)
    return mismatch == 0
